apiVersion: broker.amq.io/v2alpha4
kind: ActiveMQArtemis
metadata:
  name: poc-aao
spec:
  deploymentPlan:
    size: 2
    image: placeholder
    persistenceEnabled: true
    messageMigration: true
    storage:
      size: 2Gi
    resources:
      limits:
        cpu: "2000m"
        memory: "4096Mi"
      requests:
        cpu: "250m"
        memory: "512Mi"
  acceptors:
  - name: artemis
    protocols: 'amqp,core'
    port: 61617
    sslEnabled: true
    sslSecret: poc-broker-jks
    expose: true
  adminUser: admin
  adminPassword: changeme
  console:
    expose: true
